<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Ingresar</name>
   <tag></tag>
   <elementGuidId>3899132c-e714-4cd3-917c-dc7dfd6d6eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CtrlMenuPortal_lnkIngresar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CtrlMenuPortal_lnkIngresar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4d4b9ce-7e5b-4fcd-8f4f-ff52cd421b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>MostrarLogin();</value>
      <webElementGuid>1220d48f-5cce-4fc9-8352-980508cf08c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CtrlMenuPortal_lnkIngresar</value>
      <webElementGuid>b85e02d1-fdab-4652-9115-d401e6e46798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CtrlMenuPortal$lnkIngresar','')</value>
      <webElementGuid>89f4cdc7-b29f-4025-9ac6-5bf2fc19808a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Ingresar
                    </value>
      <webElementGuid>7dcee4bf-529a-4d84-aa25-bf423b3c7c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CtrlMenuPortal_lnkIngresar&quot;)</value>
      <webElementGuid>193b5347-0978-491c-a9fb-15ee3d068c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CtrlMenuPortal_lnkIngresar']</value>
      <webElementGuid>232d8a1c-e5d4-431d-9e82-894f5d1a970d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav']/div/div/ul[2]/li/a</value>
      <webElementGuid>4fe6311d-7797-469a-8ebf-6720a5c567d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención al usuario'])[1]/following::a[1]</value>
      <webElementGuid>e64bb643-3763-489e-8635-aa45b8f2255d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores'])[1]/following::a[2]</value>
      <webElementGuid>699cf946-83c1-469c-ac38-3c71dc4fa6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CtrlMenuPortal$lnkIngresar','')&quot;)]</value>
      <webElementGuid>2912ffeb-8f6b-4789-9c42-056032baa456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>57d54c0f-0410-4133-8f59-b36db08b62be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CtrlMenuPortal_lnkIngresar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CtrlMenuPortal$lnkIngresar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '
                        
                        Ingresar
                    ' or . = '
                        
                        Ingresar
                    ')]</value>
      <webElementGuid>64569e81-bf76-4650-848a-78014de882ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
