<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_UrgenciaNormal</name>
   <tag></tag>
   <elementGuidId>e1d66b08-eccd-4bd0-a1f6-4841f3062976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rdbUrgenciaNormal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rdbUrgenciaNormal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39a7022c-4c4e-4426-bf35-776a87bd916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rdbUrgenciaNormal</value>
      <webElementGuid>f6b7c9fc-ba10-4c6e-9f16-77818145a7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>33f0d944-4043-4f4a-b5e9-7e55fb225388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rdbUrgencia</value>
      <webElementGuid>93efcaa1-1201-4f8b-af17-2ecb5597d858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbUrgenciaNormal</value>
      <webElementGuid>48e4fc89-8ac7-4b9a-88a1-7f34d2fe5221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>004c3f3b-27e1-48fe-80fd-9973f410921c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:habilitaJustificacion();</value>
      <webElementGuid>7fba483b-a6c5-4546-bacc-3120d34cec82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rdbUrgenciaNormal&quot;)</value>
      <webElementGuid>55e854f1-e7c2-431f-99e4-811a730911c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rdbUrgenciaNormal']</value>
      <webElementGuid>130eab83-4a28-4f5a-a723-8267898eee99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_updatePanel']/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>7750207d-f316-4bac-8301-c71f42e2e71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>57802127-cee6-4a17-8d76-97d8a0c43777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rdbUrgenciaNormal' and @type = 'radio' and @name = 'ctl00$CPH1$rdbUrgencia' and @checked = 'checked']</value>
      <webElementGuid>49c4162c-92f9-4157-baf7-6df97c8bb5bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
